# ── Phase 5 ── App: Exposer ───────────────────────────────────────────────────
# REQUIRES: GCR pull secret + image tag from Arcanna team.
# ─────────────────────────────────────────────────────────────────────────────
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arcanna-exposer
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: arcanna

  source:
    repoURL: https://github.com/gn-cin-cout/arcanna-helm
    targetRevision: HEAD
    path: charts/modular-service
    helm:
      valueFiles:
        - ../../envs/gke-sandbox/_common.yaml
        - ../../envs/gke-sandbox/services/exposer.yaml
      parameters:
        - name: image.tag
          value: "ARCANNA_IMAGE_TAG"

  destination:
    server: https://kubernetes.default.svc
    namespace: arcanna

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
