apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-helm
  namespace: argocd
spec:
  project: arcanna-project
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: 23.0.4
    helm:
      values: |
        replicaCount: 2
        service:
          type: LoadBalancer
        resources:
          requests:
            memory: 64Mi
            cpu: 100m
          limits:
            memory: 128Mi
            cpu: 200m
  destination:
    server: https://kubernetes.default.svc
    namespace: arcanna
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
